config/routes.rb
Rails.application.routes.draw do
  root to: "clearance_batches#index"
  resources :clearance_batches, only: [:index, :show, :create]
  resources :items, path: :inventory_overview, only: :index
end

app/models/clearance_batch.rb
class ClearanceBatch < ActiveRecord::Base

  has_many :items

  def total_cost
    item_price_list.inject { |sum, x| sum + x }.to_f
  end

  def average_price
    total_cost / item_price_list.size
  end

  private

  def item_price_list
    items.pluck(:price_sold)
  end
end

app/models/item.rb
class Item < ActiveRecord::Base

  CLEARANCE_PRICE_PERCENTAGE  = BigDecimal.new("0.75")
  HIGH_PRICE_ITEMS = ["pants", "dress"]
  SIZES = { S: "Small", M: "Medium", L: "Large", ANY: "One Size Fits All" }

  belongs_to :style
  belongs_to :clearance_batch

  scope :sellable, -> { where(status: 'sellable') }
  scope :sweaters, -> { where(["style_id=? OR style_id=?",1,2]) }
  scope :tops, -> { where(style_id: 3) }
  scope :dresses, -> { where(["style_id=? OR style_id=?",4,5]) }
  scope :scarves, -> { where(style_id: 7) }
  scope :pants, -> { where(["style_id=? OR style_id=?",6,8]) }

  def clearance!
    update_attributes!(status: 'clearanced',
                       price_sold: clearance_price,
                       sold_at: DateTime.now)
  end

  def acceptably_clearance_priced?
    acceptable_price = HIGH_PRICE_ITEMS.include?(style.type.downcase) ? 5 : 2
    clearance_price >= acceptable_price
  end

  def clearance_price
    style.wholesale_price * CLEARANCE_PRICE_PERCENTAGE
  end

  def human_readable_size
    SIZES[size.upcase.to_sym]
  end
end

app/models/style.rb
class Style < ActiveRecord::Base
  self.inheritance_column = :_type_disabled
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clearance_batches_controller.rb
require 'csv'

class ClearanceBatchesController < ApplicationController
  before_action :check_valid_inputs, only: :create
  before_action :set_batch_ids, only: :create

  def index
    @accept_loose = params[:loose] == "true"
    @clearance_batches = ClearanceBatch.all
  end

  def show
    @batch = ClearanceBatch.find(params[:id])
  end

  def create
    clearancing_status = ClearancingService.new.clearance_batch(@batch)
    set_alert_messages(clearancing_status)
    action = { action: :index }
    action[:loose] = true if params[:loose]
    redirect_to action
  end

  private

  def check_valid_inputs
    if params[:csv_file]
      check_valid_file
    elsif params[:loose]
      check_valid_input_string
    end
  end

  def check_valid_file
    if params[:csv_batch_file] == nil
      message = "You did not chose a file to upload"
    elsif !(params[:csv_batch_file].original_filename.split(".").last == "csv")
      # would want to check mime type on a production application
      message = "The file you uploaded was not a CSV file"
    end

    if message
      flash[:alert] = message
      redirect_to action: :index
    end
  end

  def check_valid_input_string
    if params[:ids] == ""
      message = "You did not input anything"
    elsif params[:ids] =~ /[^,\d\s]+/
      message = "You submitted illegal characters. Please submit only comma seperated numbers"
    end

    if message
      flash[:alert] = message
      redirect_to action: :index, loose: true
    end
  end

  def set_batch_ids
    if params[:csv_batch_file]
      @batch = []
      CSV.foreach(params[:csv_batch_file].tempfile, headers: false) do |row|
        @batch << row[0].to_i
      end
    elsif params[:ids]
      @batch = params[:ids].gsub(" ", "").split(",").map!(&:to_i)
    end
  end

  def set_alert_messages(clearancing_status)
    clearance_batch = clearancing_status.clearance_batch
    alert_messages = []

    if clearance_batch.persisted?
      flash[:notice]  = "#{clearance_batch.items.count} items clearanced in batch #{clearance_batch.id}"
    else
      alert_messages << "No new clearance batch was added"
    end

    if clearancing_status.errors.any?
      alert_messages << "#{clearancing_status.errors.count} item ids raised errors and were not clearanced"
      clearancing_status.errors.each {|error| alert_messages << error }
    end
    flash[:alert] = alert_messages.join("<br/>") if alert_messages.any?
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    if params[:by_batch]
      @batches = ClearanceBatch.all
      @batchless_items = Item.where(clearance_batch_id: nil)
      return render :batch_index
    else
      @items = Item.all.order(:status)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clearance_batches/index.html.erb
<div class="input-form">
  <% if @accept_loose %>
    <%= render "forms/loose_id_form" %>
  <% else %>
    <%= render "forms/csv_upload_form" %>
  <% end %>
</div>

<% if @clearance_batches.any?  %>
  <input class= "index-export" type="button" onclick="tableToExcel('main', 'newfile')" value="Export to Excel">
  <table id="main" class="clearance-batches data-table">
    <thead>
      <tr>
        <th>Batch Id</th>
        <th>Date clearanced</th>
        <th>Number of Items Clearanced</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%- @clearance_batches.each do |clearance_batch| -%>
        <tr>
          <td>Clearance Batch <%= clearance_batch.id %></td>
          <td><%= l(clearance_batch.created_at, format: :short) %></td>
          <td><%= clearance_batch.items.count %></td>
          <td><%= link_to("View Clearance Report", clearance_batch_path(clearance_batch)) %></td>
        </tr>
      <%- end -%>
    </tbody>
  </table>
<% else %>
  <div class="no-content">
    <h1>You have not clearanced any batches yet. Use the form above to set batches of items to status: 'clearance'.</h1>
  </div>
<% end %>

app/views/clearance_batches/show.html.erb
<%= render "items/batch", batch: @batch %>

app/views/forms/_csv_upload_form.html.erb
<h2>Clearance Batches From a File</h2>

<%= form_tag(clearance_batches_path, multipart: true, class: 'form-inline', role: 'form') do %>
  <div class="form-group">
    <%= hidden_field_tag "csv_file", true %>
    <%= file_field_tag 'csv_batch_file', class: 'csv-upload form-control'%>
  </div>
  <%= button_tag 'upload batch file', id: "submit", class: 'btn btn-primary', data: { disable_with: "Submitting..." } %>
<% end %>

<a href="/?loose=true" class="switch btn btn-success">Switch to Id Input</a>

app/views/forms/_loose_id_form.html.erb
<h2>Clearance Batches By Entering Ids</h2>

<%= form_tag(clearance_batches_path, class: 'form-inline loose', role: 'form') do %>
  <div class="form-group">
    <h4>Enter or scan in ids seprated by commas ie: 1, 13, 5</h4>
    <h6>Click and drag on the bottom right corner to expand the box</h6>
    <%= text_area_tag 'ids',"", class: 'id-input form-control' %>
    <%= hidden_field_tag "loose", true %>
  </div>
  <%= button_tag 'submit ids', class: 'btn btn-primary', data: { disable_with: "Submitting..." } %>
<% end %>

<a href="/?loose=false" class="switch btn btn-success">Switch to CSV Input</a>

app/views/items/_batch.html.erb
<h3>Batch <%= batch.id %></h3>

<input type="button" onclick="tableToExcel('batch-<%= batch.id %>', 'newfile')" value="Export to Excel">
<table id="batch-<%= batch.id %>" class="clearance-batch data-table">

  <%= render "tables/item_header" %>
  <tbody>
    <%= render partial: "items/item", collection: batch.items %>
  </tbody>

  <%= render "tables/batch_statistics", batch: batch %>
</table>

app/views/items/_item.html.erb
<% style = item.style %>
<% item.price_sold ||= 0.00 %>
<% date = item.sold_at.blank? ? nil : item.sold_at.strftime("%D") %>

<tr class="item">
  <td><%= item.id %></td>
  <td><%= style.id %></td>
  <td><%= style.type %></td>
  <td class="name"><%= style.name %></td>
  <td><%= item.human_readable_size %></td>
  <td><%= item.color %></td>
  <td><%= item.status %></td>
  <td><%= '%.2f' % item.price_sold %></td>
  <td><%= date %></td>
</tr>

app/views/items/batch_index.html.erb
<% if @batches.any? || @batchless_items.any? %>

  <% if @batches.any? %>
    <h1>Items By Batch</h1>

    <%= render partial: "batch", collection: @batches %>
    <hr class="thick">
  <% end %>

  <% if @batchless_items.any? %>
    <h1>Items Not In Batches</h1>

    <input type="button" onclick="tableToExcel('no-batch', 'newfile')" value="Export to Excel">

    <%= render "tables/loose_item_statistics", items: @batchless_items %>
    <table id="no-batch" class="items-index data-table">
      <%= render "tables/item_header" %>
      <tbody>
        <%= render partial: "item", collection: @batchless_items %>
      </tbody>
    </table>
  <% end %>

<% else %>
  <div class="no-content">
    <h1>There are currently no items in the system.</h1>
  </div>
<% end %>

app/views/items/index.html.erb
<input type="button" onclick="tableToExcel('items', 'newfile')" value="Export to Excel">

<%= render "tables/loose_item_statistics", items: @items %>
<table id="items" class="items-index data-table">
  <%= render "tables/item_header" %>
  <tbody>
    <%= render partial: "item", collection: @items %>
  </tbody>
</table>

app/views/layouts/_flash_notices.html.erb
<%- if flash[:notice] -%>
  <div class="alert alert-info" role="alert">
    <%= flash[:notice].html_safe %>
  </div>
<%- end -%>

<%- if flash[:alert] -%>
  <div class="alert alert-danger" role="alert">
    <%= flash[:alert].html_safe %>
  </div>
<%- end -%>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Retail Stock Clearance Tool</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Clearance Items<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li>
              <%= link_to "Clearance By Batch", root_path %>
            </li>
            <li>
              <%= link_to "Clearance By Id", root_path(loose: true) %>
            </li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">View All Items<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li>
              <%= link_to "View Items By Id", items_path %>
            </li>
            <li>
              <%= link_to "View Items By Batch", items_path(by_batch: true) %>
            </li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
  <hr class="thick">
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TakeHomeChallenge</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>

  <!-- data tables cdn -->
  <script type="text/javascript" src="http://cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js"></script>
  <link rel="stylesheet" type="text/css" href="http://cdn.datatables.net/1.10.7/css/jquery.dataTables.min.css">
  <%= csrf_meta_tags %>

</head>
<body>

  <div class="container <%= controller_name %> <%= action_name %>">
    <%= render "layouts/header" %>
    <%= render "layouts/flash_notices" %>
    <%= yield %>
  </div>

</body>
</html>

app/views/tables/_batch_statistics.html.erb
<tbody class="statistics">
  <tr>
    <th>Total Items</th>
    <th>Sweaters</th>
    <th>Tops</th>
    <th>Dresses</th>
    <th>Scarves</th>
    <th>Pants</th>
    <th>Average Price</th>
    <th>Total Price</th>
    <th></th>
  </tr>
  <tr>
    <td><%= batch.items.count %></td>
    <td><%= batch.items.sweaters.count %></td>
    <td><%= batch.items.tops.count %></td>
    <td><%= batch.items.dresses.count %></td>
    <td><%= batch.items.scarves.count %></td>
    <td><%= batch.items.pants.count %></td>
    <td><%= '%.2f' % batch.average_price %></td>
    <td><%= '%.2f' % batch.total_cost %></td>
    <td></td>
  </tr>
</tbody>

app/views/tables/_item_header.html.erb
<thead>
  <tr>
    <th>Item Id</th>
    <th>Style Id</th>
    <th>Type</th>
    <th class="name">Name</th>
    <th>Size</th>
    <th>Color</th>
    <th>Status</th>
    <th>Clearance Price</th>
    <th>Sold On</th>
  </tr>
</thead>

app/views/tables/_loose_item_statistics.html.erb
<table class="above">
    <thead class="statistics">
      <tr>
        <th>Total Items</th>
        <th>Sweaters</th>
        <th>Tops</th>
        <th>Dresses</th>
        <th>Scarves</th>
        <th>Pants</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
      <tr>
        <td><%= items.count %></td>
        <td><%= items.sweaters.count %></td>
        <td><%= items.tops.count %></td>
        <td><%= items.dresses.count %></td>
        <td><%= items.scarves.count %></td>
        <td><%= items.pants.count %></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
    </thead>
</table>